name: task1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  firebase_core: ^2.20.0
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  flutter_carousel_slider: ^1.1.0
  pinput: ^3.0.1
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  toggle_switch: ^2.1.0
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


dependences:
  Shared Preferences:1 '<newest version>'

 
 

  

   

flutter:
  uses-material-design: true
  assets:
  - assets/task1.webp
  - assets/camera1.png
  - assets/arrow1.png
  - assets/e.jpg
  - assets/i.jpg
  - assets/yellow.png
  - assets/violet.png
  - assets/home.png
  - assets/transaction.png
  - assets/Add.png
  - assets/Budget.png
  - assets/profile.png
  - assets/toggle.gif  
  - assets/Illustration1.png 
  - assets/Illustration2.png 
  - assets/Illustration3.png 
  - assets/checkbox.png
  - assets/google.png                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              