// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTUvbRouRS7jfod6CCedAN1a546cbHVls',
    appId: '1:987712563166:web:11e9dc7bfe832a52d9df4f',
    messagingSenderId: '987712563166',
    projectId: 'verification-88871',
    authDomain: 'verification-88871.firebaseapp.com',
    storageBucket: 'verification-88871.appspot.com',
    measurementId: 'G-J23D0X7H6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXsqvQPwB3nlDl0R6ocOoW2MaFAGMdc4I',
    appId: '1:987712563166:android:992cda5f9d134f40d9df4f',
    messagingSenderId: '987712563166',
    projectId: 'verification-88871',
    storageBucket: 'verification-88871.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhfk6PVkOpX0kp4Nvxfp6q0mARvK83bdk',
    appId: '1:987712563166:ios:34ef282251797c53d9df4f',
    messagingSenderId: '987712563166',
    projectId: 'verification-88871',
    storageBucket: 'verification-88871.appspot.com',
    iosBundleId: 'com.example.task1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhfk6PVkOpX0kp4Nvxfp6q0mARvK83bdk',
    appId: '1:987712563166:ios:f464c5fbe0a8e116d9df4f',
    messagingSenderId: '987712563166',
    projectId: 'verification-88871',
    storageBucket: 'verification-88871.appspot.com',
    iosBundleId: 'com.example.task1.RunnerTests',
  );
}
